
# TODO: Specify some branches 
# TODO: Run on Mono / Roslyn

language: cscharp
# mono: none
# dotnet: 3.1.302

install:
  - nuget install xunit.runners -Version 2.4.1 -OutputDirectory testrunner


# jobs:
#   include:
#     - dotnet: 3.1.302
#       mono: none
#     - mono: latest

# script:
#   - dotnet restore
#   - dotnet test



