
# TODO: Specify some branches 
# TODO: Run on Mono / Roslyn

language: cscharp
# mono: none
dotnet: 3.1.302

before_install:
  - sudo apt-get install nuget

install:
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner


jobs:
  include:
    - dotnet: 3.1.302
      mono: none
    # - mono: latest

script:
  - dotnet restore
  - dotnet test



